### ISSUE TITLE
remove build_vignettes = TRUE in installation instructions

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/inbodb#32]
Users that do not have access to Futon and Cydonia, cannot build the vignette and get an error when trying to install the package.  By simply removing `build_vignettes = TRUE` in our installation instructions, users are less encouraged to install the vignette and less likely to encounter this error.  As the vignette is available online, this seems a good solution for me.

What do you think, @ElsDeBie and @hansvancalster ?

**Comment by hansvancalster** [comment]
I agree

**Comment by florisvdh** [comment]
In `watina`, vignettes can be built because the involved chunks are not evaluated, while their output has been hardcoded in the vignettes. The drawback is more maintenance (updating included output when functions get updated), but it's an alternative anyway. It's also needed to render them on the pkgdown website by GH Actions I guess.

As long as vignettes can only be compiled with a database connection, then I also agree it's better to follow your suggestion @ElsLommelen.
