### ISSUE TITLE
main instead of master

### ISSUE THREAD

**Issue by ElsDeBie** [inbo/inbodb#40]
After the update yesterday to R. I got the same error as before: 
"Error in (function (classes, fdef, mtable) : 
unable to find an inherited method for function ‘dbQuoteLiteral’ for signature ‘"Microsoft SQL Server"’

Hans discovered it was because of working in the main instead of master ... I noticed I 'm again only having a main instead of master. I will delete my local project and pull the version of github again.
A more sustainable solution might be needed?

**Comment by ElsDeBie** [comment]
I guess I missed as now the master is called main

**Comment by ElsLommelen** [comment]
Eh, I don't understand completely.  There seems to be no general problem, as I am unable to reproduce your problem here.  So I'm afraid this problem has to be solved on your computer.

Concerning the branch name: we renamed 'master' to 'main' for this package (as the term master refers to slavery), so you will have to use 'main' here.  I'm sure other INBO packages will do the same (and I will shortly change the Github course material), so you better get used to a 'main' branch.  ;-)

**Comment by ElsLommelen** [comment]
@ElsDeBie Guess this issue can be closed?

**Comment by ElsDeBie** [comment]
> @ElsDeBie Guess this issue can be closed?

Yes, it can be closed! thanks for all the work done !!

**Comment by ElsLommelen** [comment]
Thank you for all your help!  (Finally I added the new version yesterday, so the coding club will use the new version next week.)
